-- QUERY-1 Total orders per city
SELECT  r.city,
		COUNT(o.order_id) AS Total_orders
FROM orders AS o
JOIN restaurants r
ON o.restaurant_id = r.restaurant_id
GROUP BY r.city
ORDER BY Total_orders DESC;

-- QUERY-2  Revenue generated by each food item
SELECT  mi.item_name,
		SUM(mi.price*od.quantity) AS revenue
FROM menu_items mi
JOIN order_details od
ON mi.item_id = od.item_id
GROUP BY mi.item_name
ORDER BY revenue DESC;

-- QUERY-3 Top 5 spending customers
SELECT  c.customer_name,
		SUM(mi.price*od.quantity) AS Spending
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
JOIN order_details od 
ON o.order_id = od.order_id
JOIN menu_items mi
ON od.item_id = mi.item_id
GROUP BY c.customer_name
ORDER BY Spending DESC
LIMIT 5;

-- QUERY-4 Restaurant-wise orders count
SELECT  r.rest_name,
		COUNT(o.order_id) AS Total_count
FROM restaurants r 
JOIN orders o 
ON r.restaurant_id = o.restaurant_id
GROUP BY r.rest_name
ORDER BY Total_count DESC;

-- QUERY-5 Average order value by city
SELECT  c.city,
		AVG(mi.price*od.quantity) AS avg_amount
FROM customers c
JOIN orders o 
ON c.customer_id = o.customer_id
JOIN order_details od 
ON o.order_id = od.order_id
JOIN menu_items mi
ON od.item_id = mi.item_id
GROUP BY c.city
ORDER BY avg_amount DESC;

-- QUERY-6  Monthly order Trends
SELECT  month(order_date) AS month_number,
		monthname(order_date) AS order_month,
        COUNT(order_id) AS Total_orders
FROM orders
GROUP BY month_number, order_month
ORDER BY month_number;

-- QUERY-7 Top 3 cities by Revenue
SELECT c.city,
		SUM(mi.price*od.quantity) AS total_revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_details od ON o.order_id = od.order_id
JOIN menu_items mi ON od.item_id = mi.item_id
GROUP BY c.city
ORDER BY total_revenue DESC
LIMIT 3;

-- QUERY-8 Number of Unique Customer per city
SELECT  city, 
		COUNT(DISTINCT customer_id) AS unique_customers
FROM customers
GROUP BY city
ORDER BY unique_customers DESC;

-- QUERY-9 Most Frequntly ordered items
SELECT  mi.item_name,
		SUM(od.quantity) AS frequently_ordered
FROM menu_items mi
JOIN order_details od
ON mi.item_id = od.item_id
GROUP BY mi.item_name
ORDER BY frequently_ordered DESC;

-- QUERY-10 Restaurants with low order COUNT less than 30 
SELECT  r.rest_name,
		COUNT(o.order_id) AS total_orders
FROM restaurants r
JOIN orders o 
ON r.restaurant_id = o.restaurant_id
GROUP BY r.rest_name
HAVING total_orders < 30
ORDER BY total_orders DESC;